name: tourapp
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  

  webview_flutter: ^0.3.16
  i18n_extension: ^1.2.0
  flappy_search_bar: 1.4.1
  intl_translation: ^0.17.7
  scoped_model: ^1.0.1
  google_maps_flutter: ^0.5.21+12
  bloc: ^0.15.0
  sembast: ^2.1.2+3
  material_design_icons_flutter: ^3.4.4795
  extended_image:
     git:
       url: https://github.com/fluttercandies/extended_image.git
       ref: dev
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons. 

  cupertino_icons: ^0.1.2
  camera:
  dio: ^3.0.7
  path:
  sailor: ^0.5.0
  chopper: ^3.0.1
  get_it: ^2.0.1 
  flutter_bloc: ^0.21.0
  equatable: ^0.4.0
  dartz: ^0.8.6
  # Remote API
  data_connection_checker: ^0.3.4
  connectivity: ^0.4.3+7
  http: ^0.12.0+2
  shimmer: ^1.0.1
  retrofit: ^1.0.1+1
  google_fonts_arabic:
           git: git://github.com/emadomedher/google-fonts-arabic.git
           version:  ^1.1.7
  # Local cache
  shared_preferences: ^0.5.3+4
  moor_flutter: ^2.0.0
  geolocator: ^5.1.5
  latlong: ^0.6.1
  location: ^2.3.5
  fluttertoast: ^3.1.3
  flutter_slidable: ^0.5.3
  provider: ^3.0.0+1  
  simple_search_bar: ^0.1.7
  path_provider: ^1.3.0
  hive: ^1.1.1
  sqflite: ^1.1.8
  hive_flutter: ^0.2.1
  bloc_pattern: ^2.3.2
  rxdart: ^0.22.0
  card_settings: ^1.5.5
  photo_view: ^0.3.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.0
  flutter_launcher_icons: "^0.7.3"
  hive_generator: ^0.5.2
  build_runner: ^1.7.0
  chopper_generator: ^3.0.1
  moor_generator: ^2.0.0
  retrofit_generator: ^1.0.2+2
  
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
flutter_icons:
  android: true
  ios: true
  image_path: "lib/assets/images/icon2.jpeg"
# The following section is specific to Flutter.
flutter:
  
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   
    - lib/lang/ar.json
    - lib/lang/en.json
    - lib/assets/images/icon.png
    - lib/assets/images/icon2.jpg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
     - family: Caveat
       fonts:
          - asset: lib/assets/fonts/Caveat-Bold.ttf
          - asset: lib/assets/fonts/Caveat-Regular.ttf
  #         style: italic
  #   - family: Trajan Pro
  
     - family: FredokaOne
       fonts:
          - asset: lib/assets/fonts/FredokaOne-Regular.ttf

     - family: SeymourOne
       fonts:
          - asset: lib/assets/fonts/SeymourOne-Regular.ttf
  #  - lib/fonts/MyFlutterApp.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
